version: "3.9"

networks:
  axess_dev:
    driver: bridge

services:
  ms:
    image: stream-ms:latest
    container_name: stream-read-writer
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: live
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_QUEUES: finsc
      BATCH_SIZE: 50
      BLOCK_TIMEOUT: 5
      # For Sentinel:
      # REDIS_USE_SENTINEL: "true"
      # REDIS_SENTINELS: "redis-sentinel-1:26379,redis-sentinel-2:26379"
      # REDIS_MASTER_NAME: "mymaster"
    networks:
      - axess_dev
